services:
  backend:
    build: ./backend/Vendas
    container_name: vendas-backend
    working_dir: /var/www
    volumes:
      - ./backend/Vendas:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
  frontend:
    build: ./frontend/projeto-vendas
    container_name: vendas-frontend
    working_dir: /app
    volumes:
      - ./frontend/projeto-vendas:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
  db:
    image: mysql:8.0
    container_name: vendas-db
    restart: always
    environment:
      MYSQL_DATABASE: vendas
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
